### ISSUE TITLE
Info about 3rd GameObject with remote user stream.

### ISSUE THREAD

**Issue by vinmobpro** [AgoraIO/Video-Call-for-Mobile-Gaming#17]
In the official tutorial on Medium and YouTubeof AGORA, There were 2 GameObjects created - One was CUBE and other was CYLINDER. They both render local stream. 

When 2 devices are connected, A third GameObject appears with remote user stream.

Then what's the use of both Cube and Cylinder then ? Even in tutorial 3 GameObjects appear in the end which looks really ugly.

Can someone pin point how can I access the GameObject which renders remote user stream ? I am trying to put AR tracker on Remote User's stream using AR Core. Maybe my understanind ig wrong otherwise.

Any helpful suggestion will be appreciated. Thanks !

**Comment by zhangtao1104** [comment]
The demo which render the video into 3d gameobject was just show you that the sdk can do it.
You can also render the video into a rawImage and adjust the size of the video.

If you want to use ARCore ,you can capture the video by yourself and pushVideoFrame to agora sdk.

**Comment by vinmobpro** [comment]
Hi !

Thanks for getting back. Can you please elaborate the last part ?

Capture the video myself means ? And PushVideoFrame is what in general
terms ?

Thanks !

**Comment by icywind** [comment]
Hi Vinmobpro, while waiting for the answer on PushVideoFrame, I can qualify a little bit on your original question. 

>> how can I access the GameObject which renders remote user stream ? 

Basically, in your project you probably will generate a 3D object from a prefab.  All you need to do is to attach the VideoSurface script to that prefab.  And your controller gets the VideoSurface component from the object instantiated from the prefab.  Note that you will want to put that VideoSurface script to the same level of the MeshRender or RawImage component.

Hope this helps.

**Comment by vinmobpro** [comment]
So, Here are a few concerns -

1. VideoSurface.cs doesn't work with RawImage or anything other than a 3D
object.
2. I want control on the object which is instantiated (ie - Remote User
stream ). Since It is instantiated at runtime - What logic should I use to
perform any operation on it ?
3. I didn't get anything after you said - "*All you need to do is attach
VideoSurface script to the prefab*".

I am on the verge of the deadline. I would really appreciate if you provide
guidance from someone expert in Unity.

Also in your demos, You have 3 objects. The point you want to prove is just
this - That you attach VideoSurface to any GameObject (3D) and it works ?
If that is your sole reason, It's not a good idea. The demos should be
simple and to the point. You can add extra info in description or extra
notes. Thanks !

Best,
Vineet

**Comment by icywind** [comment]
Hi Vineet,

If you read my last comment more carefully,  I said "**put that VideoSurface script to the same level of the MeshRender or RawImage component**"  So it is not any GameObject.  The primitive objects that you can create from Editor hierarchy (Cube, Plane, Sphere, etc) come with a MeshRender.  VideoSurface will work with that.

To further address your concerns, here are some helpers - 
1) RawImage support is not automatically in the current version of the SDK.  You can modify the VideoSurface to make it assign main material texture to that.  The next release of the SDK will include an update to that.
2) Back to what I said earlier - I would create a prefab, say it is the cube as an example. I would attach the VideoSurface script to it and save it.  In the code (in the onUserJoined delegate) I would use GameObject.Instantiate(prefab) to create new instance of that.  Consider the code that you can find in [HelloUnityVideo.cs](https://github.com/AgoraIO/Video-Call-for-Mobile-Gaming/blob/master/Hello-Video-Unity-Agora/Assets/HelloUnityVideo.cs), create your object there instead of creating that Plane.  Then assign the UID you got from the delegate callback through that VideoSurface's SetForUser() method.  
3) Perhaps you have a different architecture than the MVC pattern that I used frequently. I apologize for the confusion.  So I won't comment more on how you should program it. Let me know if you have any other concern regarding the SDK or API calls.

-Regards,

RC
